// Generates data/mapDots.ts: a dotted map of North Africa & the Middle East.
// Run with `npm run build:map` after changing the region or client list.
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoContains } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const world = require("world-atlas/countries-50m.json");
const countries = feature(world, world.objects.countries).features;

const REGION = { lonMin: -14, lonMax: 60, latMin: 12, latMax: 46 };
const STEP = 0.9;
const WIDTH = 1000;
const kx = Math.cos((30 * Math.PI) / 180);
const scale = WIDTH / ((REGION.lonMax - REGION.lonMin) * kx);
const HEIGHT = Math.round((REGION.latMax - REGION.latMin) * scale);

const CLIENT_IDS = {
  "012": "DZ", "275": "PS", "792": "TR", "760": "SY", "818": "EG", "682": "SA", "784": "AE",
};

const project = (lon, lat) => [
  +((lon - REGION.lonMin) * kx * scale).toFixed(1),
  +((REGION.latMax - lat) * scale).toFixed(1),
];

// Pre-filter countries whose bbox touches the region.
const candidates = countries.filter((f) => {
  const coords = JSON.stringify(f.geometry.coordinates).match(/-?\d+\.?\d*/g).map(Number);
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (let i = 0; i < coords.length; i += 2) {
    minX = Math.min(minX, coords[i]); maxX = Math.max(maxX, coords[i]);
    minY = Math.min(minY, coords[i + 1]); maxY = Math.max(maxY, coords[i + 1]);
  }
  return maxX >= REGION.lonMin && minX <= REGION.lonMax && maxY >= REGION.latMin && minY <= REGION.latMax;
});

const dots = [];
for (let lat = REGION.latMax; lat >= REGION.latMin; lat -= STEP) {
  const row = Math.round((REGION.latMax - lat) / STEP);
  // Offset every other row for a hex-like pattern.
  const offset = row % 2 ? STEP / 2 : 0;
  for (let lon = REGION.lonMin + offset; lon <= REGION.lonMax; lon += STEP) {
    const hit = candidates.find((f) => geoContains(f, [lon, lat]));
    if (!hit) continue;
    const [x, y] = project(lon, lat);
    dots.push(x, y, CLIENT_IDS[hit.id] ? 1 : 0);
  }
}

const markers = [
  { code: "EG", name: "Egypt", city: "Cairo", lon: 31.24, lat: 30.04 },
  { code: "DZ", name: "Algeria", city: "Algiers", lon: 3.06, lat: 36.75 },
  { code: "PS", name: "Palestine", city: "Ramallah", lon: 35.2, lat: 31.9 },
  { code: "SY", name: "Syria", city: "Damascus", lon: 36.29, lat: 33.51 },
  { code: "TR", name: "Türkiye", city: "Ankara", lon: 32.86, lat: 39.93 },
  { code: "SA", name: "Saudi Arabia", city: "Riyadh", lon: 46.72, lat: 24.69 },
  { code: "AE", name: "UAE", city: "Abu Dhabi", lon: 54.37, lat: 24.45 },
].map(({ lon, lat, ...m }) => {
  const [x, y] = project(lon, lat);
  return { ...m, x, y };
});

const out = `// Generated by scripts/build-map.mjs. Do not edit by hand.
export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};
/** Flat list of [x, y, isClient] triples. */
export const MAP_DOTS: number[] = [${dots.join(",")}];
export const MAP_MARKERS = ${JSON.stringify(markers, null, 2)} as const;
`;
writeFileSync(new URL("../data/mapDots.ts", import.meta.url), out);
console.log(`dots: ${dots.length / 3}, size ${WIDTH}x${HEIGHT}`);
